language: python

python:
    - "3.4"

env:
    - DJANGO_SETTINGS_MODULE=__.settings.local_uranusjr

install:
    - pip install -q -r requirements.txt
    - pip install -q -r requirements-dev.txt

script:
    - python manage.py test
